services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - ${PORT_MONGODB}:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - ${PORT_MONGO_EXPRESS}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${PORT_MONGODB}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  Flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT_FLASK}:5000
    depends_on:
      - mongodb
      - mongo-express
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=${PORT_MONGODB}
      - MONGO_DB=Bdd_user
      - MONGO_COLLECTION=user
